SELECT I.SUMMARY, IL.NAME
FROM ISSUES I
JOIN ISSUESLISTS IL ON IL.ID = I.ISSUESLISTS_ID;

SELECT I.SUMMARY, U.FIRSTNAME, U.LASTNAME
FROM ISSUES I
JOIN USERS U ON I.USER_ID_ASSIGNEDTO = U.ID

SELECT U.FIRSTNAME, U.LASTNAME, IL.NAME AS ISSUESLISTS_NAME, COUNT(*) AS ISSUES_COUNT
FROM USERS U JOIN ISSUES I ON I.USER_ID_ASSIGNEDTO = U.ID
JOIN ISSUESLISTS IL ON IL.ID = I.ISSUESLISTS_ID
GROUP BY U.ID, IL.NAME
ORDER BY U.LASTNAME, U.FIRSTNAME;