CREATE TABLE ISSUESLISTS
(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100)
);

CREATE TABLE ISSUES
(
    ID SERIAL PRIMARY KEY ,
    ISSUESLISTS_ID BIGINT UNSIGNED NOT NULL,
    USER_ID  BIGINT UNSIGNED NOT NULL,
    SUMMARY VARCHAR (100),
    DESCRIPTION VARCHAR (2000),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

INSERT INTO ISSUESLISTS (NAME) VALUES ("ToDo");
INSERT INTO ISSUESLISTS (NAME) VALUES ("In progress");
INSERT INTO ISSUESLISTS (NAME) VALUES ("Done");

INSERT INTO ISSUES (ISSUESLISTS_ID, USER_ID, SUMMARY, DESCRIPTION) VALUES (1, 1, "Zakupy", "Zakupy w Lidlu i Biedronce");
INSERT INTO ISSUES (ISSUESLISTS_ID, USER_ID, SUMMARY, DESCRIPTION) VALUES (1, 3, "Zakupy", "Zakupy w Lidlu i Biedronce");
INSERT INTO ISSUES (ISSUESLISTS_ID, USER_ID, SUMMARY, DESCRIPTION) VALUES (1, 2, "Zakupy", "Zakupy w Lidlu i Biedronce");
INSERT INTO ISSUES (ISSUESLISTS_ID, USER_ID, SUMMARY, DESCRIPTION) VALUES (1, 3, "Czyszczenie", "Czyszczenie domu");
INSERT INTO ISSUES (ISSUESLISTS_ID, USER_ID, SUMMARY, DESCRIPTION) VALUES (1, 1, "Nauka", "Nauka do egzaminu");

INSERT INTO ISSUES (ISSUESLISTS_ID, USER_ID, SUMMARY, DESCRIPTION) VALUES (2, 3, "Zakupy", "Zakupy w Lidlu i Biedronce");
INSERT INTO ISSUES (ISSUESLISTS_ID, USER_ID, SUMMARY, DESCRIPTION) VALUES (2, 2, "Zakupy", "Zakupy w Lidlu i Biedronce");
INSERT INTO ISSUES (ISSUESLISTS_ID, USER_ID, SUMMARY, DESCRIPTION) VALUES (2, 1, "Zakupy", "Zakupy w Lidlu i Biedronce");
INSERT INTO ISSUES (ISSUESLISTS_ID, USER_ID, SUMMARY, DESCRIPTION) VALUES (2, 1, "Czyszczenie", "Czyszczenie domu");
INSERT INTO ISSUES (ISSUESLISTS_ID, USER_ID, SUMMARY, DESCRIPTION) VALUES (2, 2, "Nauka", "Nauka do egzaminu");

INSERT INTO ISSUES (ISSUESLISTS_ID, USER_ID, SUMMARY, DESCRIPTION) VALUES (3, 2, "Zakupy", "Zakupy w Lidlu i Biedronce");
INSERT INTO ISSUES (ISSUESLISTS_ID, USER_ID, SUMMARY, DESCRIPTION) VALUES (3, 1, "Zakupy", "Zakupy w Lidlu i Biedronce");
INSERT INTO ISSUES (ISSUESLISTS_ID, USER_ID, SUMMARY, DESCRIPTION) VALUES (3, 3, "Zakupy", "Zakupy w Lidlu i Biedronce");
INSERT INTO ISSUES (ISSUESLISTS_ID, USER_ID, SUMMARY, DESCRIPTION) VALUES (3, 2, "Czyszczenie", "Czyszczenie domu");
INSERT INTO ISSUES (ISSUESLISTS_ID, USER_ID, SUMMARY, DESCRIPTION) VALUES (3, 3, "Nauka", "Nauka do egzaminu");